#!/bin/bash

declare -a iconlist=(\
 "hit_icon_0km" \
 "hit_icon_5km" \
 "hit_icon_10km" \
 "hit_icon_15km" \
 "hit_icon_20km" \
 "hit_icon_25km" \
 "hit_icon_30km" \
 "hit_icon_35km" \
 "hit_icon_35km" \
 "hit_icon_40km" \
 "hit_icon_45km" \
 "hit_icon_50km" \
 "hit_icon_55km" \
 "hit_icon_60km" \
 "hit_icon_65km" \
 "hit_icon_70km" \
 "hit_icon_75km" \
 "hit_icon_80km" \
 "hit_icon_85km" \
 "hit_icon_90km" \
 "hit_icon_100km" \
 "hit_icon_120km" \
 "hit_icon_150km" \

 "hit_icon_0pers" \
 "hit_icon_groepje" \

 "hit_icon_k_ks" \
 "hit_icon_k_kv" \
 "hit_icon_k_kgv" \

 "hit_icon_geenrugz" \
 "hit_icon_hike" \
 "hit_icon_hikevr" \

 "hit_icon_staand" \
 "hit_icon_tent" \
 "hit_icon_nacht" \
 "hit_icon_gebouw" \
 "hit_icon_friet" \
 "hit_icon_tent_opgezet" \

 "hit_icon_gas" \
 "hit_icon_opvuur" \
 "hit_icon_stafkookt" \
 "hit_icon_vuur" \

 "hit_icon_buitenland" \
 "hit_icon_geenmobieltje" \
 "hit_icon_insigne" \
 "hit_icon_mobieltje" \
 "hit_icon_rolstoel" \
 "hit_icon_vraagt" \
 "hit_icon_idee" \
 "hit_icon_geenalcohol" \

 "hit_icon_vol" \
 "hit_icon_todo" \
 "hit_icon_info" \
 "hit_icon_web" \
 "hit_icon_aantaldagen1" \
 "hit_icon_aantaldagen2" \
 "hit_icon_aantaldagen3" \
 "hit_icon_aantaldagen4" \

 "hit_icon_auto" \
 "hit_icon_bootslaap" \
 "hit_icon_fiets" \
 "hit_icon_fiets60" \
 "hit_icon_kano" \
 "hit_icon_kano10" \
 "hit_icon_zeilboot" \
 "hit_icon_zwem" \
 "hit_icon_trein" \
 "hit_icon_motor" \
)
